export const mockParts = [
  {
    id: '1',
    name: 'iPhone 13 Screen',
    compatibility: 'Apple iPhone 13',
    category: 'Screens',
    price: 89.99,
    quantity: 24,
    stock: 'In Stock',
    image: '/parts/iphone-screen.jpg',
  },
  {
    id: '2',
    name: 'Samsung S22 Battery',
    compatibility: 'Samsung Galaxy S22',
    category: 'Batteries',
    price: 34.99,
    quantity: 12,
    stock: 'Low Stock',
    image: '/parts/iphone-battery.jpg',
  },
  {
    id: '3',
    name: 'USB-C Flex Cable',
    compatibility: 'Google Pixel 6 / 7',
    category: 'Flex Cables',
    price: 12.99,
    quantity: 45,
    stock: 'In Stock',
    image: '/parts/flex-cable.jpg',
  },
  {
    id: '4',
    name: 'Screen Protector Kit',
    compatibility: 'Universal',
    category: 'Tools',
    price: 5.99,
    quantity: 102,
    stock: 'In Stock',
    image: '/parts/repair-tools.jpg',
  },
  {
    id: '5',
    name: 'iPhone 14 Pro Max Screen',
    compatibility: 'Apple iPhone 14 Pro Max',
    category: 'Screens',
    price: 119.99,
    quantity: 3,
    stock: 'Low Stock',
    image: '/parts/iphone-screen.jpg',
  },
  {
    id: '6',
    name: 'Replacement Battery Kit',
    compatibility: 'Apple iPhone 12-14 Series',
    category: 'Batteries',
    price: 28.99,
    quantity: 0,
    stock: 'Out of Stock',
    image: '/parts/iphone-battery.jpg',
  },
  {
    id: '7',
    name: 'Charging Port Flex Cable',
    compatibility: 'Samsung Galaxy A Series',
    category: 'Flex Cables',
    price: 15.99,
    quantity: 8,
    stock: 'Low Stock',
    image: '/parts/charging-port.jpg',
  },
  {
    id: '8',
    name: 'Professional Repair Toolkit',
    compatibility: 'Universal',
    category: 'Tools',
    price: 49.99,
    quantity: 6,
    stock: 'Low Stock',
    image: '/parts/repair-tools.jpg',
  },
];
